### ISSUE TITLE
Go-to-Player in rankings is inconsistent

### ISSUE THREAD

**Issue by Cepheid-UK** [w3champions/w3champions-ui#201]
Intended functionality: 
1. When a user searches a player name, the list will scroll to show the player.
2. When a user clicks on the division icon on a player's profile, the rankings will open and scroll to the player.

Issue:
1. This is inconsistent for even slightly less than full screen browser windows.
2. This does not work.

**Comment by jj-apps** [comment]
@Cepheid-UK Are you able to reproduce the scroll issue on demand?

The only issue I see with scrolling is when going from the Grand Master page to a lower division with more than 30 ranks.

**Comment by Cepheid-UK** [comment]
Tested and the functionality works, I'll check through to make sure I understand what you did for the future, then merge, thanks!
