### ISSUE TITLE
FFA grid needs redesign

### ISSUE THREAD

**Issue by Cepheid-UK** [w3champions/w3champions-ui#205]
FFA grid tends to clip the portraits of players with particularly long battle.net tags, a different design for this grid is needed. 

A small improvement to maximise the space available was already tried and hasn't fully resolved the issue.

![ffagrid](https://user-images.githubusercontent.com/40397054/96872305-5f6d8000-146b-11eb-8c7f-803fc0b531b2.PNG)

**Comment by jj-apps** [comment]
@Cepheid-UK are two rows okay?

![image](https://user-images.githubusercontent.com/3699727/97664475-c543a400-1a37-11eb-9f13-1c8a4923328d.png)

**Comment by Cepheid-UK** [comment]
Sure that looks better already. I had the idea of 1 player on the top row and 3 on the bottom, but honestly whatever you think looks good, at the moment how it works isn't great.

**Comment by alocate** [comment]
I personally like the winner on the top row centered and the 3 other players below.

**Comment by jj-apps** [comment]
@alocate @Cepheid-UK 

It looks like there are 3 different ways this is displayed.

1. Matches page - Match in progress (names aren't displayed)
2. Matches page - Finished (1 winner and 3 losers)
3. Profile Matches tab - current user is always the first team listed

I think the 1 winner on top and 3 on the bottom will work for scenario 2, but what about the other two scenarios?

**Comment by JKoehler11** [comment]
Personally, I think for matches in progress, that it could look like 4v4 and just stack them all in one column.

To be consistent, the users can just be stacked everywhere the match is shown.

**Comment by Cepheid-UK** [comment]
I'd be fine with that.

**Comment by jj-apps** [comment]
@Cepheid-UK Is this okay?

![image](https://user-images.githubusercontent.com/3699727/99899253-0c9f0800-2c65-11eb-812b-be005e6ef892.png)

**Comment by Cepheid-UK** [comment]
Closed with #291
