### ISSUE TITLE
Icon selection frequently hides special icons on less than full screen window

### ISSUE THREAD

**Issue by Cepheid-UK** [w3champions/w3champions-ui#207]
The icon selection panel should scale to the users window better, the special icons at the bottom are partially-to-completely hidden if the user is on anything less than full-screen window.

![iconselection](https://user-images.githubusercontent.com/40397054/96873520-f6870780-146c-11eb-85dd-bff4bf404ba7.PNG)

**Comment by jensk1** [comment]
#220 I edited that part of PlayerAvatar, that the dialog is scrollable if the height gets too small, this should fix the problem that icons are partially hidden. Also the icons can still be clicked in that case by scrolling down.

**Comment by Cepheid-UK** [comment]
Thanks for the PR #220 solves.
