### ISSUE TITLE
Times for game starts are not consistent between server time / local time

### ISSUE THREAD

**Issue by Cepheid-UK** [w3champions/w3champions-ui#225]
Match history shows times in Local time (GMT in screenshot below)

![time1](https://user-images.githubusercontent.com/40397054/97188554-8a254480-179b-11eb-98b9-d6cc77e3004f.PNG)

Match summary page shows times in CET:

![time2](https://user-images.githubusercontent.com/40397054/97188595-97daca00-179b-11eb-9644-cbd5499f4ed7.PNG)

**Comment by JKoehler11** [comment]
Should it be showing in UTC or the user's timezone? Could use momentjs to determine the timezone from the browser and then show that everywhere on the site to be consistent.

**Comment by Cepheid-UK** [comment]
Not sure which we SHOULD show, I personally would prefer local time, but as long as we commit to one of them that's better than splitting.

**Comment by Cepheid-UK** [comment]
I'm an idiot, that is the game length lol.
