### ISSUE TITLE
Adding a dropdown menu for gamemode in the MMR distribution page

### ISSUE THREAD

**Issue by alocate** [w3champions/w3champions-ui#242]
Right now it only shows the MMR distribution for solo (and only europe? not sure). Would be sweet to have the same for other gamemodes, like some other pages in the Statistics section already have.

https://www.w3champions.com/OverallStatistics/mmr-distribution

**Comment by modmoto** [comment]
afair it is bound to the gateway that you selected in the league overview.

**Comment by jensk1** [comment]
I wanted to tackle this, however if i understand correctly, the API Service does only provide interface for season.
https://github.com/w3champions/w3champions-statistic-service/blob/master/W3ChampionsStatisticService/W3ChampionsStats/MmrDistribution/MmrDistributionHandler.cs#L17

This should also be extendended, to optionally filter by game mode. Also maybe mmr distribution per Race is interesting aswell? I heard humans are underpowered all the time ;). 

If possible i could contribute to statistics-service aswell, but i am not quiet sure how to get into it (and if this is a good first issue).

**Comment by Cepheid-UK** [comment]
> I wanted to tackle this, however if i understand correctly, the API Service does only provide interface for season.
> https://github.com/w3champions/w3champions-statistic-service/blob/master/W3ChampionsStatisticService/W3ChampionsStats/MmrDistribution/MmrDistributionHandler.cs#L17
> 
> This should also be extendended, to optionally filter by game mode. Also maybe mmr distribution per Race is interesting aswell? I heard humans are underpowered all the time ;).
> 
> If possible i could contribute to statistics-service aswell, but i am not quiet sure how to get into it (and if this is a good first issue).

If you read up in #new-devs-chat on discord, abeninski has been discussing how to set up the stats service locally in order to make changes to it. He also provided some old data to use for testing. You also need to install mongodb, there is an outstanding task to update the stats-service with a wiki page that explains how to set up the dev environment. I'll make an issue there.

**Comment by modmoto** [comment]
I will actually write up a small docu for that
@abeninski I will do the documentation right now.

**Comment by jensk1** [comment]
@Cepheid-UK i got it working with the new docu.
But i cant find a #new-dev-chat in discord, is it internal?

**Comment by jensk1** [comment]
I think this issue can be closed since it is live already. 
If there is still something to do let me know

**Comment by modmoto** [comment]
jeah, u are right =)
