### ISSUE TITLE
Replace old race icons in match history and player match history with new one

### ISSUE THREAD

**Issue by Kaenshin** [w3champions/w3champions-ui#252]
Change icons in match history and player match history from square portraits to the same race plates icons as in ranking page.

Those icons
![image](https://user-images.githubusercontent.com/33329764/97694370-be05b000-1aa2-11eb-9079-9253f946bbf1.png)
apply here
Player match history
![image](https://user-images.githubusercontent.com/33329764/97694228-8eef3e80-1aa2-11eb-9848-048cc7fecb3b.png)
Match history
![image](https://user-images.githubusercontent.com/33329764/97694259-97477980-1aa2-11eb-9802-dc26a89c9346.png)

**Comment by SergeyKhval** [comment]
opened #257
