### ISSUE TITLE
Match history stats show incorrect win/loss vs specific opponent

### ISSUE THREAD

**Issue by Cepheid-UK** [w3champions/w3champions-ui#256]
The: 
"Vs Player
Wins X / Losses Y (ZZ.Z%)"

Component does not always show the correct values.

Most tests show the initial season selected will show fine, but changing season will cause it to be wrong.

S4: (5 wins, 4 losses, correct)
![Screenshot from 2020-11-01 09-08-10](https://user-images.githubusercontent.com/40397054/97798912-62623080-1c22-11eb-905f-ba09bc7e3dc2.png)

S2: (5 wins, negative 4 losses, incorrect - actually 1 win 0 losses)
![Screenshot from 2020-11-01 09-08-24](https://user-images.githubusercontent.com/40397054/97798908-5b3b2280-1c22-11eb-8a0b-07049972b9ce.png)

**Comment by SergeyKhval** [comment]
Opened #258

**Comment by Cepheid-UK** [comment]
Fixed by #258
