### ISSUE TITLE
Player statistics sometimes don't fully show up

### ISSUE THREAD

**Issue by marco93f** [w3champions/w3champions-ui#278]
As it appears, for all players who played every 1vs1 map at least once during season 4, stats corresponding to Ruins of Azshara LV won't show up.
For example:
https://www.w3champions.com/player/Unique%2322912/statistics (ROA stats missing)
https://www.w3champions.com/match/5fa5677aef7438b9a5d65b7f (a game of his played on ROA)

**Comment by aaronjewell** [comment]
This appears to duplicate #301. There are 11 possible maps, and the table will only display 10. Should be resolved by #308.

**Comment by aaronjewell** [comment]
Resolved by #308
