### ISSUE TITLE
Interface in the Admin page to add News

### ISSUE THREAD

**Issue by Cepheid-UK** [w3champions/w3champions-ui#295]
Modmoto moved the news items to the database, so we can now support updating the news through the website admin page.

I know Warcraft3.info uses TinyMCE to write WYSIWYG HTML, might be worth using too?

I also wonder if storing the news in raw HTML rather than string text might have some advantages, e.g. adding images, video embeds, fancy stuff to news posts?

**Comment by modmoto** [comment]
We had html earlier but none coders should be able to do that aswell. Right now it supports markdown, so technically images aswell. But this might get weird when we have to scale them for different sizes. Also we need a Upload function for images aswell unless we reference from the static content but then it gets more complicated for floss and other non techies

**Comment by Cepheid-UK** [comment]
Agree on uploading images. I think Abeninski had a good hosting solution for the in-game assets, so using that would make implementing anything that we want on both webstite + in-game easier.

**Comment by aaronjewell** [comment]
I suggest tiptap for the text editor. There is also a Vuetify version that will integrate nicely with the site theme (although this is just admin facing anyway...)

It will take a URL for image inserts, and putting the images on a CDN is a great choice. Perhaps a separate image upload Vue component would make sense so you can achieve the dual purpose @Cepheid-UK mentions for in-game + website assets.

**Comment by Cepheid-UK** [comment]
That does sound ideal, I think resolving the whole admin functions and such will be necessary before we can get to the 2nd phase of auto-tours, which will probably be our next priority after S6 launches.

**Comment by Cepheid-UK** [comment]
I'm going to close this issue since this feature was added now. I'll open another if we have more specific feature requests.

**Comment by aaronjewell** [comment]
@Cepheid-UK - Going to resurrect this, as I had some time to try out a WYSIWYG implementation that turned out to work pretty well. Let me know if you want to move forward with it.

PR #347
