### ISSUE TITLE
Loading screen one-liners

### ISSUE THREAD

**Issue by weidenbach** [w3champions/w3champions-ui#300]
- [x] Change ingame UI to display a random one-liner instead of current text
- [x] Add backend support to provide data to ingame-ui
- [x] Add frontend support to allow admins to edit the pool of displayable one-liners

More ways to communicate to the community are helpful to inform everyone about what's to know about everything W3C related.
A great way to do this, as shown by for example Hearthstone, is to display a one-liner text message during loading screens, since players are waiting anyway.
This would replace the current message "Joining ladder game, please wait...". The checkbox "Do not restart search if game creation fails" would be moved to pregame settings.

Some categories could be:
"Did you know",
upcoming features,
season start/end info,
behavioural rules,
donation request to support
etc.

Currently the match found takes about ~10 seconds to turn into the loading screen. During this time the one-liners can be displayed.
Ugly mockup (Kenshin will fix 😄):
![loading screen issue](https://user-images.githubusercontent.com/73471359/100774616-8b810700-3402-11eb-909f-e1c4d8c14bc0.png)

**Comment by Cepheid-UK** [comment]
Very cool, I hope we can store these in the DB so they can easily be editable!

**Comment by modmoto** [comment]
I think storing it in the DB should be mandatory, so Floss and Miyagi can change it. It is also easier for us to change stuff quickly. For the first iteration we can surely just hardcode a few messages and swap them with the DB generated ones later.

**Comment by Cepheid-UK** [comment]
Do you think we're getting enough of these kinds of feature requests that we might want to integrate a CMS for authed users on the website?

With bans, tournaments, showmatches, in-game messages, chat commands, etc, feels like we might be close to needing one?

**Comment by modmoto** [comment]
a full blown cms? Dont know, dont think we have that much content, tbh. We mostly have news, bans (which are kind of not a content) and now those messages. I mean, saving some simple objects in the db is quite easy. For the news it took me a few hours from UI to db with the complete crud, where UI was actually the most tricky part.

**Comment by weidenbach** [comment]
Oh I thought the admin page on the website is already used for that kind of stuff. I wanted to add it to that page so that anyone authorized can make changes to the list of messages, then it can be edited more easily by people that don't know how to access the db also. I guess it's not super needed, but it shouldn't take that long to add that to the website i figured.

btw. which service would I use to store the messages? w3champions-statistic-service ?

**Comment by Cepheid-UK** [comment]
I had heard some CMS's were quite lightweight and made this sort of thing easier, but idk, maybe not worth.

It just seemed like we were adding a lot of stuff that was dynamic recently, and potentially opening functionality to more non-techy users.

> but it shouldn't take that long to add that to the website i figured.

This is sort of why I suggested a CMS plugin, since we are discussing adding so many more features to the admin page, and pretty soon we'll need role functionality for like tourney orgas for example.

> btw. which service would I use to store the messages? w3champions-statistic-service ?

stats service communicates with the DB, so that will indeed be where you need to work.

**Comment by abeninski** [comment]
No CMS please. CMS is overkill which is always hard to support

**Comment by modmoto** [comment]
> Oh I thought the admin page on the website is already used for that kind of stuff. 

Yes it is, news and bans are configured there. I dont have a problem giving more people access to that page. I would not start adding roles or stuff like that. BEing in the dev team should be enough. Maybe add a "ChangedBy" attribute aswell, so we can track it a little better.

And I second Abe, dont think a CMS is really worth it. We still woudl have to trigger the API, do some UI work to integrate. I think when we have more than 10 content things, this might be an option. But still not that fond of a CMS. 

One thing that comes to mind are the faqs, thez could go to the admin page aswell. Right now they are a json in a repo that floss can access.

**Comment by Cepheid-UK** [comment]
All good, just thought I'd ask the question.

I do think we will need 1 more role access though in the forseeable future: A role with access to creation of tournaments, but that would be isolated to the /tournaments page.

**Comment by weidenbach** [comment]
So I have everything ready. This is how it would look ingame:
![grafik](https://user-images.githubusercontent.com/73471359/101286593-9c0ef400-37eb-11eb-9bbb-fbd4ea0c0f65.png)

If UI PR request is merged we can add some tips and then I'll do a PR for the ingame-ui

**Comment by Cepheid-UK** [comment]
Looks good, but just a note that the S5 end date is still being discussed!

**Comment by weidenbach** [comment]
I just copied that from the discord command 😅

**Comment by modmoto** [comment]
btw, the ui for this is allready on prod, i guess the backend aswell.

**Comment by weidenbach** [comment]
I noticed, because someone added a tip with "Thanks for playing W3Champions!", which showed up during my ingame-UI test.

I wanted to push the ingame-UI yesterday, but noticed a problem. The UI stays when the loading bar appears, which is bad, because they overlap. Once that is fixed the whole thing is ready. I don't know how to get the event that the game is loading, will check later. Maybe you can give me a lead :D?

**Comment by Cepheid-UK** [comment]
> "Thanks for playing W3Champions!"

Ha that was me, when I was checking it on test.w3champions.com. It's should only be in the test database.

**Comment by weidenbach** [comment]
This stuff is added, closed.
