### ISSUE TITLE
Autumn Leaves doesn't appear on statistics page, even when its' played

### ISSUE THREAD

**Issue by tlansec** [w3champions/w3champions-ui#301]
https://www.w3champions.com/player/iDentify%2311833/statistics

I suspect this is due to a capped # of maps being displayed? or perhaps its something else?

**Comment by Cepheid-UK** [comment]
Did a preliminary investigation:

- the stats for AL are correctly logging in the database
![correctindb](https://user-images.githubusercontent.com/40397054/101362992-b94dcc00-3898-11eb-85d8-ec4db871e5fe.PNG)

- the frontend is displaying all the data it's receiving correctly
![frontend](https://user-images.githubusercontent.com/40397054/101363096-de423f00-3898-11eb-94c6-1c66f56fd401.PNG)

- the frontend is only receiving the first 10 maps of data in the database, and not receving number 11 ('autumnleaves201016')

**Comment by modmoto** [comment]
maybe create the issue in the statisticservice

**Comment by Cepheid-UK** [comment]
> maybe create the issue in the statisticservice

I went back in time and did just that!

https://github.com/w3champions/w3champions-statistic-service/issues/106

**Comment by modmoto** [comment]
hehe xD

**Comment by Cepheid-UK** [comment]
#308 has resolved some cases for this but not all. More investigation still requried.
